CREATE TABLE ARIADNE_OPERATORS
(
  OPERATOR_ID   INTEGER IDENTITY PRIMARY KEY,
  OPERATOR_CLASS_NAME VARCHAR(32) NOT NULL,
  DESCRIPTION VARCHAR(256) NOT NULL,
  CONSTRAINT UNQ_CLASS UNIQUE (OPERATOR_CLASS_NAME)
);

CREATE TABLE ARIADNE_OPERAND_OWNERS
(
  OPERAND_OWNER_ID   INTEGER IDENTITY PRIMARY KEY,
  OPERAND_OWNER_CLASS_NAME VARCHAR(256) NOT NULL,
  OPERAND_OWNER_INPUT VARCHAR(4096) NOT NULL,
  CONSTRAINT UNQ_OO_CLASS UNIQUE (OPERAND_OWNER_CLASS_NAME)
);
CREATE TABLE ARIADNE_OPERATIONS
(
  OPERATION_ID   INTEGER IDENTITY PRIMARY KEY,
  LH_OPERAND_OWNER_ID   INTEGER ,
  OPERATOR_ID   INTEGER ,
  RH_OPERAND_OWNER_ID   INTEGER ,
  DESCRIPTION VARCHAR(4000) NOT NULL,
  CONSTRAINT UNQ_OPER_CLASS UNIQUE (LH_OPERAND_OWNER_ID,OPERATOR_ID,RH_OPERAND_OWNER_ID)
);

INSERT INTO ARIADNE_OPERATORS (OPERATOR_CLASS_NAME, DESCRIPTION) 
  VALUES
  ('NotEqual','!='),
  ('Add','+'),
  ('Divide','/'),
  ('LessThanEqual','<='),
  ('Equal','=='),
  ('Power','pow'),
  ('Multiply','*'),
  ('Max','max'),
  ('Min','min'),
  ('And','&&'),
  ('GreaterThanEqual','>='),
  ('LessThan','<'),
  ('Or','||'),
  ('GreaterThan','>'),
  ('Subtract','-');
