//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.16 at 11:26:07 AM PST 
//


package org.bongiorno.ariadne.implementations.xml.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.org.bongiorno.ariadne.implementation.xml.jaxb package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Input_QNAME = new QName("", "Input");
    private final static QName _FQCN_QNAME = new QName("", "FQCN");
    private final static QName _Description_QNAME = new QName("", "Description");
    private final static QName _ID_QNAME = new QName("", "ID");
    private final static QName _LHO_QNAME = new QName("", "LHO");
    private final static QName _OP_QNAME = new QName("", "OP");
    private final static QName _RHO_QNAME = new QName("", "RHO");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.org.bongiorno.ariadne.implementation.xml.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OperationEntry }
     * 
     */
    public OperationEntry createOperationEntry() {
        return new OperationEntry();
    }

    /**
     * Create an instance of {@link KnowledegeBaseEntry }
     * 
     */
    public KnowledegeBaseEntry createKnowledegeBaseEntry() {
        return new KnowledegeBaseEntry();
    }

    /**
     * Create an instance of {@link OperandOwnerEntry }
     * 
     */
    public OperandOwnerEntry createOperandOwnerEntry() {
        return new OperandOwnerEntry();
    }

    /**
     * Create an instance of {@link OperatorEntry }
     * 
     */
    public OperatorEntry createOperatorEntry() {
        return new OperatorEntry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Input")
    public JAXBElement<String> createInput(String value) {
        return new JAXBElement<String>(_Input_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FQCN")
    public JAXBElement<String> createFQCN(String value) {
        return new JAXBElement<String>(_FQCN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ID")
    public JAXBElement<Integer> createID(Integer value) {
        return new JAXBElement<Integer>(_ID_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LHO")
    public JAXBElement<Integer> createLHO(Integer value) {
        return new JAXBElement<Integer>(_LHO_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OP")
    public JAXBElement<Integer> createOP(Integer value) {
        return new JAXBElement<Integer>(_OP_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RHO")
    public JAXBElement<Integer> createRHO(Integer value) {
        return new JAXBElement<Integer>(_RHO_QNAME, Integer.class, null, value);
    }

}
