//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.16 at 11:26:07 AM PST 
//


package org.bongiorno.ariadne.implementations.xml.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}OperationEntry" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}OperandOwnerEntry" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}OperatorEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operationEntry",
    "operandOwnerEntry",
    "operatorEntry"
})
@XmlRootElement(name = "KnowledegeBaseEntry")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
public class KnowledegeBaseEntry {

    @XmlElement(name = "OperationEntry")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    protected List<OperationEntry> operationEntry = new ArrayList<OperationEntry>();
    @XmlElement(name = "OperandOwnerEntry")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    protected List<OperandOwnerEntry> operandOwnerEntry = new ArrayList<OperandOwnerEntry>();
    @XmlElement(name = "OperatorEntry")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    protected List<OperatorEntry> operatorEntry = new ArrayList<OperatorEntry>();

    /**
     * Gets the value of the operationEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operationEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperationEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperationEntry }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    public List<OperationEntry> getOperationEntry() {
        return this.operationEntry;
    }

    public void setOperationEntry(List<OperationEntry> operationEntry) {
        this.operationEntry = operationEntry;
    }

    public void addOperationEntry(OperationEntry ope) {
        operationEntry.add(ope);
    }
    /**
     * Gets the value of the operandOwnerEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operandOwnerEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperandOwnerEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperandOwnerEntry }
     * 
     *
     * @return
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    public List<OperandOwnerEntry> getOperandOwnerEntry() {
        return this.operandOwnerEntry;
    }

    public void setOperandOwnerEntry(List<OperandOwnerEntry> operandOwnerEntry) {
        this.operandOwnerEntry = operandOwnerEntry;
    }

    public void addOperandOwnerEntry(OperandOwnerEntry ooe) {
        operandOwnerEntry.add(ooe);
    }

    /**
     * Gets the value of the operatorEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operatorEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperatorEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperatorEntry }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    public List<OperatorEntry> getOperatorEntry() {
        return this.operatorEntry;
    }

    public void setOperatorEntry(List<OperatorEntry> operatorEntry) {
        this.operatorEntry = operatorEntry;
    }

    public void addOperatorEntry(OperatorEntry oe) {
        operatorEntry.add(oe);
    }

    public void addOperatorEntry(String fqcn, String description) {
        operatorEntry.add(new OperatorEntry(operatorEntry.size() + 1,fqcn,description));
    }
}
