//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.16 at 11:26:07 AM PST 
//


package org.bongiorno.ariadne.implementations.xml.jaxb;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.bongiorno.ariadne.interfaces.OperandOwner;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ID"/>
 *         &lt;element ref="{}FQCN"/>
 *         &lt;element ref="{}Input"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "fqcn",
    "input"
})
@XmlRootElement(name = "OperandOwnerEntry")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
public class OperandOwnerEntry {

    @XmlElement(name = "ID")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    protected int id;
    @XmlElement(name = "FQCN", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    protected String fqcn;
    @XmlElement(name = "Input", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    protected Object input;


    public OperandOwnerEntry() {
    }

    public OperandOwnerEntry(int id, String fqcn, Object input) {
        this.id = id;
        this.fqcn = fqcn;
        this.input = input;
    }

    public OperandOwnerEntry(OperandOwner oo) {
        this(oo.getId(),oo.getClass().getName(),oo.getInput());
    }

    /**
     * Gets the value of the id property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the fqcn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    public String getFQCN() {
        return fqcn;
    }

    /**
     * Sets the value of the fqcn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    public void setFQCN(String value) {
        this.fqcn = value;
    }

    /**
     * Gets the value of the input property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    public Object getInput() {
        return input;
    }

    /**
     * Sets the value of the input property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-01-16T11:26:07-08:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    public void setInput(String value) {
        this.input = value;
    }

}
